// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameApkinfo = "apkinfo"

// Apkinfo mapped from table <apkinfo>
type Apkinfo struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // version发布的Id，主键自增
	ApkIcon     string `gorm:"column:apk_icon" json:"apk_icon"`                   // icon图片
	ApkName     string `gorm:"column:apk_name" json:"apk_name"`                   // apk的名字
	AppID       string `gorm:"column:app_id;not null" json:"app_id"`              // apk的包名
	LastRelease int32  `gorm:"column:last_release" json:"last_release"`           // apk的最后一个Release版本
}

// TableName Apkinfo's table name
func (*Apkinfo) TableName() string {
	return TableNameApkinfo
}
