// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVersion = "versions"

// Version mapped from table <versions>
type Version struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`       // version发布的Id，主键自增
	Name           string `gorm:"column:name;not null" json:"name"`                        // 当前Apk的版本名
	Code           int32  `gorm:"column:code;not null;default:-1" json:"code"`             // 当前Apk的VersionCode
	Changelog      string `gorm:"column:changelog" json:"changelog"`                       // 更改内容日志
	Downloads      int32  `gorm:"column:downloads;not null;default:0" json:"downloads"`    // 下载次数
	ApkURL         string `gorm:"column:apk_url" json:"apk_url"`                           // 下载地址
	QrcodeURL      string `gorm:"column:qrcode_url" json:"qrcode_url"`                     // 下载地址的Qrcode
	ApkID          int32  `gorm:"column:apk_id;not null" json:"apk_id"`                    // apk的ID
	ReleaseVersion bool   `gorm:"column:release_version;default:0" json:"release_version"` // 是否是一个Release版本
	Timestamp      int64  `gorm:"column:timestamp;not null;default:0" json:"timestamp"`
}

// TableName Version's table name
func (*Version) TableName() string {
	return TableNameVersion
}
