// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"com.wangzhumo.distribute/models/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newVersion(db *gorm.DB) version {
	_version := version{}

	_version.versionDo.UseDB(db)
	_version.versionDo.UseModel(&model.Version{})

	tableName := _version.versionDo.TableName()
	_version.ALL = field.NewField(tableName, "*")
	_version.ID = field.NewInt32(tableName, "id")
	_version.Name = field.NewString(tableName, "name")
	_version.Code = field.NewInt32(tableName, "code")
	_version.Changelog = field.NewString(tableName, "changelog")
	_version.Downloads = field.NewInt32(tableName, "downloads")
	_version.ApkURL = field.NewString(tableName, "apk_url")
	_version.QrcodeURL = field.NewString(tableName, "qrcode_url")
	_version.ApkID = field.NewInt32(tableName, "apk_id")
	_version.ReleaseVersion = field.NewBool(tableName, "release_version")
	_version.Timestamp = field.NewInt32(tableName, "timestamp")

	_version.fillFieldMap()

	return _version
}

type version struct {
	versionDo versionDo

	ALL            field.Field
	ID             field.Int32
	Name           field.String
	Code           field.Int32
	Changelog      field.String
	Downloads      field.Int32
	ApkURL         field.String
	QrcodeURL      field.String
	ApkID          field.Int32
	ReleaseVersion field.Bool
	Timestamp      field.Int32

	fieldMap map[string]field.Expr
}

func (v version) As(alias string) *version {
	v.versionDo.DO = *(v.versionDo.As(alias).(*gen.DO))

	v.ALL = field.NewField(alias, "*")
	v.ID = field.NewInt32(alias, "id")
	v.Name = field.NewString(alias, "name")
	v.Code = field.NewInt32(alias, "code")
	v.Changelog = field.NewString(alias, "changelog")
	v.Downloads = field.NewInt32(alias, "downloads")
	v.ApkURL = field.NewString(alias, "apk_url")
	v.QrcodeURL = field.NewString(alias, "qrcode_url")
	v.ApkID = field.NewInt32(alias, "apk_id")
	v.ReleaseVersion = field.NewBool(alias, "release_version")
	v.Timestamp = field.NewInt32(alias, "timestamp")

	v.fillFieldMap()

	return &v
}

func (v *version) WithContext(ctx context.Context) *versionDo { return v.versionDo.WithContext(ctx) }

func (v version) TableName() string { return v.versionDo.TableName() }

func (v *version) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	return _f.(field.OrderExpr), true
}

func (v *version) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 10)
	v.fieldMap["id"] = v.ID
	v.fieldMap["name"] = v.Name
	v.fieldMap["code"] = v.Code
	v.fieldMap["changelog"] = v.Changelog
	v.fieldMap["downloads"] = v.Downloads
	v.fieldMap["apk_url"] = v.ApkURL
	v.fieldMap["qrcode_url"] = v.QrcodeURL
	v.fieldMap["apk_id"] = v.ApkID
	v.fieldMap["release_version"] = v.ReleaseVersion
	v.fieldMap["timestamp"] = v.Timestamp
}

func (v version) clone(db *gorm.DB) version {
	v.versionDo.ReplaceDB(db)
	return v
}

type versionDo struct{ gen.DO }

func (v versionDo) Debug() *versionDo {
	return v.withDO(v.DO.Debug())
}

func (v versionDo) WithContext(ctx context.Context) *versionDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v versionDo) Clauses(conds ...clause.Expression) *versionDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v versionDo) Not(conds ...gen.Condition) *versionDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v versionDo) Or(conds ...gen.Condition) *versionDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v versionDo) Select(conds ...field.Expr) *versionDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v versionDo) Where(conds ...gen.Condition) *versionDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v versionDo) Order(conds ...field.Expr) *versionDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v versionDo) Distinct(cols ...field.Expr) *versionDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v versionDo) Omit(cols ...field.Expr) *versionDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v versionDo) Join(table schema.Tabler, on ...field.Expr) *versionDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v versionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *versionDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v versionDo) RightJoin(table schema.Tabler, on ...field.Expr) *versionDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v versionDo) Group(cols ...field.Expr) *versionDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v versionDo) Having(conds ...gen.Condition) *versionDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v versionDo) Limit(limit int) *versionDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v versionDo) Offset(offset int) *versionDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v versionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *versionDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v versionDo) Unscoped() *versionDo {
	return v.withDO(v.DO.Unscoped())
}

func (v versionDo) Create(values ...*model.Version) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v versionDo) CreateInBatches(values []*model.Version, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v versionDo) Save(values ...*model.Version) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v versionDo) First() (*model.Version, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Version), nil
	}
}

func (v versionDo) Take() (*model.Version, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Version), nil
	}
}

func (v versionDo) Last() (*model.Version, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Version), nil
	}
}

func (v versionDo) Find() ([]*model.Version, error) {
	result, err := v.DO.Find()
	return result.([]*model.Version), err
}

func (v versionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Version, err error) {
	buf := make([]*model.Version, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v versionDo) FindInBatches(result *[]*model.Version, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v versionDo) Attrs(attrs ...field.AssignExpr) *versionDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v versionDo) Assign(attrs ...field.AssignExpr) *versionDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v versionDo) Joins(field field.RelationField) *versionDo {
	return v.withDO(v.DO.Joins(field))
}

func (v versionDo) Preload(field field.RelationField) *versionDo {
	return v.withDO(v.DO.Preload(field))
}

func (v versionDo) FirstOrInit() (*model.Version, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Version), nil
	}
}

func (v versionDo) FirstOrCreate() (*model.Version, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Version), nil
	}
}

func (v versionDo) FindByPage(offset int, limit int) (result []*model.Version, count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	if limit <= 0 {
		return
	}

	result, err = v.Offset(offset).Limit(limit).Find()
	return
}

func (v versionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v *versionDo) withDO(do gen.Dao) *versionDo {
	v.DO = *do.(*gen.DO)
	return v
}
